version: '3.3'
networks:
  proxy:
    external: true
services:
  # Minecraft Fabric Server
  mc-fabric:
      image: itzg/minecraft-server
      container_name: mc_fabric_server
      ports:
        - 25565:25565
      environment:
        TYPE: "FABRIC"
        MOTD: "Fabric Minecraft Server"
        MEMORY: "4G"
        EULA: "TRUE"
        ENABLE_RCON: "true"
        RCON_PASSWORD: ${RCON_PASSWORD}
        RCON_PORT: 28016
        restart: always
      volumes:
      - /data/minecraft-fabric:/data
      restart: unless-stopped
      networks:
        - proxy

  # Minecraft Backup Service
  mc-backup:
    image: itzg/mc-backup
    container_name: mc_backup
    # This needs to be set because backups use hostnames
    hostname: minecraftbackup
    environment:
      BACKUP_METHOD: tar
      BACKUP_INTERVAL: "6h"
      PRUNE_BACKUPS_DAYS: 3
      INITIAL_DELAY: 120
      TAR_COMPRESS_METHOD: gzip
      ZSTD_PARAMETERS: "-3 --long=25 --single-thread"
      SRC_DIR: "/data/minecraft-fabric/world"
      DEST_DIR: "/data/minecraft-backups"
      BACKUP_NAME: tableflipper-server
      RCON_HOST: mc-fabric # change this to your Minecraft docker service name
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
    volumes:
      - /data:/data
    restart: unless-stopped
    networks:
      - proxy

  # Traefik
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik_host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    command:
      --api.insecure=true
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.file.filename="dynamic_conf.yml"
      --entrypoints.http.address=:80
      --entrypoints.https.address=:443
      --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      --certificatesresolvers.letsencrypt.acme.storage=acme.json
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # let Traefik listen for Docker events
      - /data/traefik/acme.json:/acme.json
      - /data/traefik/dynamic_conf.yml:/dynamic_conf.yml
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.traefik.rule=Host(`traefik.pragmaticbeaver.eu`)"
      - "traefik.http.routers.traefik.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.pragmaticbeaver.eu`)"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.service=api@internal"

      # redirect
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"

      # authentication
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.traefik-secure.middlewares=secHeaders@file,traefik-auth"

      # config
      - "providers.file.filename=/dynamic_conf.yml"
 
  # WebDAV
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: unless-stopped
    environment:
      AUTH_TYPE: Basic
      SERVER_NAMES: webdav.pragmaticbeaver.eu
      UID: 1002
      GID: 1002
      TZ: Europe/Berlin
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: bind
        source: /data/webdav
        target: /var/lib/dav
      - /data/webdav-config/user.passwd:/user.passwd
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.webdav.rule=Host(`webdav.pragmaticbeaver.eu`)"
      - "traefik.http.routers.webdav.entrypoints=http"
      
      #- "traefik.http.middlewares.webdav-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.webdav.middlewares=webdav-https-redirect"

      # HTTPS
      - "traefik.http.routers.webdav-secure.rule=Host(`webdav.pragmaticbeaver.eu`)"
      - "traefik.http.routers.webdav-secure.entrypoints=https"
      - "traefik.http.routers.webdav-secure.tls=true"
      - "traefik.http.routers.webdav-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webdav-secure.service=webdav"

      # Port
      - "traefik.http.services.webdav.loadbalancer.server.port=80"

      # authentication
      - "traefik.http.routers.webdav-secure.middlewares=secHeaders@file"

      - "traefik.docker.network=proxy"

  # FoundryVTT services for Beaver
  foundry-beaver:
    image: felddy/foundryvtt:release
    container_name: foundry-beaver
    init: true
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - type: bind
        source: /data/webdav/data/foundry-vtt-beaver
        target: /data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.foundryvtt-beaver.rule=Host(`foundry.beaver.pragmaticbeaver.eu`)"
      - "traefik.http.routers.foundryvtt-beaver.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.foundryvtt-beaver-secure.rule=Host(`foundry.beaver.pragmaticbeaver.eu`)"
      - "traefik.http.routers.foundryvtt-beaver-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-beaver-secure.tls=true"
      - "traefik.http.routers.foundryvtt-beaver-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.foundryvtt-beaver-secure.service=foundrybeaver"

      # Port
      - "traefik.http.services.foundrybeaver.loadbalancer.server.port=30000" # FoundryVTT Port

      # redirect
      - "traefik.http.routers.foundryvtt-beaver.middlewares=foundryvtt-beaver-https-redirect"
      - "traefik.http.middlewares.foundryvtt-beaver-https-redirect.redirectscheme.scheme=https"
  
  # FoundryVTT services for WarHab
  foundry-warhab:
    image: felddy/foundryvtt:release
    container_name: foundry-warhab
    init: true
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - type: bind
        source: /home/kibin/foundry-vtt-warhab
        target: /data
      # - type: bind
      #   source: /home/warhab/foundry-vtt-warhab
      #   target: /data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD_WARHAB}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME_WARHAB}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_PASSWORD_WARHAB}
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.foundryvtt-warhab.rule=Host(`foundry.warhab.pragmaticbeaver.eu`)"
      - "traefik.http.routers.foundryvtt-warhab.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.foundryvtt-warhab-secure.rule=Host(`foundry.warhab.pragmaticbeaver.eu`)"
      - "traefik.http.routers.foundryvtt-warhab-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-warhab-secure.tls=true"
      - "traefik.http.routers.foundryvtt-warhab-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.foundryvtt-warhab-secure.service=foundrywarhab"
      - "traefik.http.services.foundrywarhab.loadbalancer.server.port=30000" # FoundryVTT Port

      # redirect
      - "traefik.http.routers.foundryvtt-warhab.middlewares=foundryvtt-warhab-https-redirect"
      - "traefik.http.middlewares.foundryvtt-warhab-https-redirect.redirectscheme.scheme=https"